version: '3'
services:
  back:
    image: aimalvin/myapp-back:latest
    ports:
      - "5000:5000"
    environment:
      CURRENT_ENVIRONMENT: development

  front:
    image: aimalvin/myapp-front:latest
    ports:
      - "80:80"
    environment:
      WS_BACK_URL: "http://host.docker.internal:5000"
